{"name": "test_a5", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "self = <ke21.test_case1.TestCase1 object at 0x000001ADB162C8D0>\n\n    def test_a5(self):\n        print(\"2222222222222\")\n>       assert 1 == 2\nE       assert 1 == 2\n\nke21\\test_case1.py:33: AssertionError"}, "attachments": [{"name": "stdout", "source": "84f640af-bc8a-47f7-9e16-9f091f51e4ec-attachment.txt", "type": "text/plain"}], "start": 1659146216953, "stop": 1659146216953, "uuid": "107395ba-daf6-46d1-af9e-231e08e14ca5", "historyId": "cf47205c3b9475ca96150e935ae62075", "testCaseId": "8e9827777fcecd6e902b2a77c664c463", "fullName": "ke21.test_case1.TestCase1#test_a5", "labels": [{"name": "feature", "value": "添加商品"}, {"name": "parentSuite", "value": "ke21"}, {"name": "suite", "value": "test_case1"}, {"name": "subSuite", "value": "TestCase1"}, {"name": "host", "value": "DESKTOP-7DB67S3"}, {"name": "thread", "value": "29504-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "ke21.test_case1"}]}