{"name": "test_a4", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "self = <ke21.test_case1.TestCase1 object at 0x000001F5E3CEEA90>\n\n    @allure.severity(\"critical\")\n    def test_a4(self):\n        print(\"2222222222222\")\n>       assert 1 == 2\nE       assert 1 == 2\n\nke21\\test_case1.py:28: AssertionError"}, "attachments": [{"name": "stdout", "source": "59bdcf80-076f-4d0e-b449-73542db5a80f-attachment.txt", "type": "text/plain"}], "start": 1659147148841, "stop": 1659147148842, "uuid": "2cbce201-549c-49fb-abae-9c8b0b96fdb9", "historyId": "c44669749b6c79ea7b5683723ae4c4df", "testCaseId": "7106e3bda248994e0d7282fedc2d9b54", "fullName": "ke21.test_case1.TestCase1#test_a4", "labels": [{"name": "feature", "value": "添加商品"}, {"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "ke21"}, {"name": "suite", "value": "test_case1"}, {"name": "subSuite", "value": "TestCase1"}, {"name": "host", "value": "DESKTOP-7DB67S3"}, {"name": "thread", "value": "28080-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "ke21.test_case1"}]}