{"name": "test_a5", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "self = <ke21.test_case1.TestCase1 object at 0x0000028EA8192AC8>\n\n    def test_a5(self):\n        print(\"2222222222222\")\n>       assert 1 == 2\nE       assert 1 == 2\n\nke21\\test_case1.py:33: AssertionError"}, "attachments": [{"name": "stdout", "source": "67cec08b-ac16-4848-a8dc-00754334f630-attachment.txt", "type": "text/plain"}], "start": 1659146401624, "stop": 1659146401624, "uuid": "8b8a77e1-0d6e-45de-b6d3-60f1d76bc9d8", "historyId": "cf47205c3b9475ca96150e935ae62075", "testCaseId": "8e9827777fcecd6e902b2a77c664c463", "fullName": "ke21.test_case1.TestCase1#test_a5", "labels": [{"name": "feature", "value": "添加商品"}, {"name": "parentSuite", "value": "ke21"}, {"name": "suite", "value": "test_case1"}, {"name": "subSuite", "value": "TestCase1"}, {"name": "host", "value": "DESKTOP-7DB67S3"}, {"name": "thread", "value": "21996-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "ke21.test_case1"}]}